services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    restart: always
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:${WORDPRESS_PATH}
    networks:
      - network
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
      # - adminer
      # - redis
      # - loupquehec
    ports:
      - 443:443
    volumes:
      - wordpress:${WORDPRESS_PATH}
    networks:
      - network
    restart: on-failure
  
  # BONUS
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - network
    restart: on-failure

  # adminer:
  #   container_name: adminer
  #   build: ./requirements/bonus/adminer
  #   depends_on:
  #     - mariadb
  #   expose:
  #     - 9000
  #   networks:
  #     - network
  #   restart: on-failure

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    ports:
      - 21:21
      - 21000-21010:21000-21010
    volumes:
      - wordpress:${WORDPRESS_PATH}
    networks:
      - network
    restart: on-failure
  
  # loupquehec:
  #   container_name: loupquehec
  #   build: ./requirements/bonus/loupquehec
  #   networks:
  #     - network
  #   restart: on-failure

  # static_page:
  #   container_name: static_page
  #   build: ./requirements/bonus/static_page
  #   networks:
  #     - network
  #   restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/lquehec/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/lquehec/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
