CREATE DATABASE {{WORDPRESS_DB_NAME}};
CREATE USER '{{WORDPRESS_DB_USER}}'@'%' IDENTIFIED BY '{{WORDPRESS_DB_PASSWORD}}';
GRANT ALL PRIVILEGES ON {{WORDPRESS_DB_NAME}}.* TO '{{WORDPRESS_DB_USER}}'@'%' IDENTIFIED BY '{{WORDPRESS_DB_PASSWORD}}';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_ROOT_PASSWORD}}';
